# Generated by Django 4.2.2 on 2023-07-17 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0003_term_class_end_term_class_start'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hris_number', models.IntegerField()),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('user_type', models.IntegerField()),
                ('status', models.IntegerField()),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UPM.college')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UPM.department')),
            ],
        ),
    ]
