# Generated by Django 4.2.2 on 2023-07-17 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0003_term_class_end_term_class_start'),
        ('accounts', '0002_referencetable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReferenceTable',
            new_name='GoogleSSOReference',
        ),
    ]
