# Generated by Django 4.2.2 on 2023-07-17 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0003_term_class_end_term_class_start'),
        ('accounts', '0003_rename_referencetable_googlessoreference'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoogleSSOReference',
            new_name='ReferenceAccount',
        ),
    ]
