# Generated by Django 4.2.2 on 2023-07-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_googlessoreference_referenceaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
