# Generated by Django 4.2.7 on 2023-12-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_authuser_can_approve_alter_authuser_can_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='college_list',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]