# Generated by Django 4.2.2 on 2023-06-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='class_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='class_start',
            field=models.DateField(null=True),
        ),
    ]
