# Generated by Django 4.2.2 on 2023-08-01 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UPM', '0003_term_class_end_term_class_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulefile',
            name='ocs',
        ),
        migrations.AddField(
            model_name='schedulefile',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
