# Generated by Django 4.2.4 on 2023-09-04 03:18

import UPM.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0005_alter_term_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalName', models.CharField(max_length=800, null=True)),
                ('additional_instructions', models.TextField(blank=True, null=True)),
                ('attachFile', UPM.models.FileField(blank=True, null=True, upload_to='attachmentsfile', verbose_name='Attach files/materials')),
            ],
        ),
    ]
