# Generated by Django 4.2.4 on 2023-09-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0006_scheduleextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleextra',
            name='attachFile',
            field=models.CharField(blank=True, max_length=8000, null=True),
        ),
    ]
