# Generated by Django 4.2.4 on 2023-09-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0007_alter_scheduleextra_attachfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='deletedDates',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
