# Generated by Django 4.2.4 on 2023-09-20 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0011_remove_schedulefile_file_schedulefile_attachfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulefile',
            old_name='attachFile',
            new_name='file',
        ),
    ]
