# Generated by Django 4.2.4 on 2023-09-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0012_rename_attachfile_schedulefile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulefile',
            name='dateSubmitted',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
