# Generated by Django 4.2.4 on 2023-10-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPM', '0014_alter_schedule_classnum'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_number', models.IntegerField(null=True)),
                ('code_name', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
