"""
Django settings for ORB project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
import dj_database_url

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-8owjc*_3p%r($gst+_=@xwb+gz1n6^0e=!e)m2$pg+45!mvr(l'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'cg#p$g+j9tax!#a3cup@1$8obt2_+&k3q+pmu)5%asj6yjpkag')
# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = False

# ALLOWED_HOSTS = ['upm-online-room-booking-system.herokuapp.com']
ALLOWED_HOSTS = ['orbsdev.upm.edu.ph', 'orbs.upm.edu.ph', '127.0.0.1']
# ALLOWED_HOSTS = ['*']


CSRF_TRUSTED_ORIGINS = ['https://orbsdev.upm.edu.ph', 'https://orbs.upm.edu.ph']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookingapp',
    'bootstrap3',
    'accounts',
    'UPM',
    'crispy_forms',
    'django_filters',
    'django_extensions',
    'bootstrap_modal_forms',
    'widget_tweaks',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'crispy_bootstrap4',
    'mathfilters',
    'social_django',
    'logger',
    'apscheduler'
]

AUTH_USER_MODEL = 'accounts.AuthUser'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

BOOTSTRAP3 = {
  'javascript_in_head': True,
}

MIDDLEWARE = [
   
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'ORB.custom_referrer.CustomReferrerPolicyMiddleware',
]


ROOT_URLCONF = 'ORB.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.media',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'bookingapp.context_processors.ADPD_notif_context',
                'social_django.context_processors.backends',
            ],
        },
    },
]

from django.contrib.messages import constants as messages


MESSAGE_TAGS = {
        messages.DEBUG: 'alert-secondary',
        messages.INFO: 'alert-info',
        messages.SUCCESS: 'alert-success',
        messages.WARNING: 'alert-warning',
        messages.ERROR: 'alert-danger',
 }

WSGI_APPLICATION = 'ORB.wsgi.application'

db_from_env = dj_database_url.config(conn_max_age=500)
DATABASES = {
    'default': {
       'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
DATABASES['default'].update(db_from_env)

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# COMMENT THIS TO GSIGNIN IN LOCAL ----------------------------------------------------

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# COMMENT THIS TO GSIGNIN IN LOCAL ----------------------------------------------------

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
# EMAIL_HOST_USER = 'appsdev@post.upm.edu.ph'
EMAIL_HOST_USER = 'no-reply-appsdev-orbs@post.upm.edu.ph'
# EMAIL_HOST_PASSWORD = 'rvlonnlqlicovqni'
# EMAIL_HOST_PASSWORD = 'bawrffkqwfyqflma'
EMAIL_HOST_PASSWORD = 'lnobxebniqgpgmpf'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
DEFAULT_FROM_EMAIL = 'no-reply-appsdev-orbs@post.upm.edu.ph'
# DEFAULT_FROM_EMAIL = 'appsdev@post.upm.edu.ph'


SOCIAL_AUTH_PIPELINE = (
    # 'social_core.pipeline.social_auth.social_details',
    # 'social_core.pipeline.social_auth.social_uid',
    'accounts.pipeline.user.user_details',
    'accounts.pipeline.user.check_user',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.social_auth.associate_by_email',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    'accounts.pipeline.user.create_faculty'
)

LOGIN_URL = 'login'
LOGOUT_URL = 'logout'

SOCIAL_AUTH_URL_NAMESPACE = 'social'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = "849909090429-pvbd00lc89kec28vl1boras1vtief5cm.apps.googleusercontent.com"
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = "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"

SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS = ['up.edu.ph', 'post.upm.edu.ph']

SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = ['']

SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS = {
    'prompt': 'select_account',
}

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/'
SOCIAL_AUTH_LOGIN_ERROR_URL = '/failedLogin/'
# SOCIAL_AUTH_STRATEGY = 'ORB.google_uri_strategy.GoogleSSOStrategy'

# FALSE THIS TO GSIGNIN IN LOCAL ----------------------------------------------------

SOCIAL_AUTH_REDIRECT_IS_HTTPS = True

# FALSE THIS TO GSIGNIN IN LOCAL ----------------------------------------------------

SOCIAL_AUTH_RAISE_EXCEPTIONS = True
SECURE_CROSS_ORIGIN_OPENER_POLICY = None

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

SEAMLESS_KEY = "TD4jxsshiQgGnJJfYuG5MMvxcrrZCbDtinPtRUHJYDGuqoN9JSyr2aArBnnxYGEJ"
