# Generated by Django 4.2.2 on 2023-08-01 01:34


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='log',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
